### PR TITLE
fix:added flag to check the user was selected any reporting period

### LINKED ISSUE #6049: Reporting Period Dropdown Issue in Emissions Module
When emissions data is imported from historical, the reporting period dropdown will change to the correct reporting period (if 2023 Q3 emissions data is imported, 2023 Q3 will be selected from the dropdown automatically). When initially selecting a view after import or switching between units in the configuration, the reporting period dropdown will select both the reporting period of the imported data and the current reporting period. The user will then have to go back into the dropdown to remove the current reporting period selection to view the imported data.

### PR DESCRIPTION
**Pull request by ergjustin**
## Ticket
[Reporting Period Dropdown Issue in Emissions Module](https://github.com/US-EPA-CAMD/easey-ui/issues/6049)

## Changes

- Added a flag to identify the user is select a reporting period date or not.
- The flag will true, when user import data or charge location or viewTemplete
- If the flag is true, push new date with existing dates

### CODE REVIEW

File: src/components/HeaderInfo/HeaderInfo.js [hunk 1]
```diff
@@ -215,6 +215,10 @@ export const HeaderInfo = ({
   const [selectedReportingPeriods, setSelectedReportingPeriods] = useState(
     currentTab?.reportingPeriods ?? []
   );
+  /* defaultReportingPeriodChanged is a flage; user selecte a reporing date or not;
+    it's changed when user manually change location or viewTemplate or when import data
+  */
+  const [defaultReportingPeriodChanged, setDefaultReportingPeriodChanged] = useState(false);
```
Comment (maxdiebold-erg) [inline src/components/HeaderInfo/HeaderInfo.js:221]: Is this flag really necessary? The issue seems to be resolved without it. Correct me if I'm wrong, but it looks like the main fix is in concatenating the new period with the previously selected ones.

**Review by maxdiebold-erg — COMMENTED** [review]
This fixed the issue! I do have one question, noted below.

File: src/components/HeaderInfo/HeaderInfo.js (hunk 1 above)
Comment (ergjustin) [reply src/components/HeaderInfo/HeaderInfo.js:221]: When a user goes directly to the imported data, the user has not selected the current year and last quarter from the reporting period list. Therefore, it is necessary to prevent it. That is why I use a flag.

Comment (maxdiebold-erg) [reply src/components/HeaderInfo/HeaderInfo.js:221]: Ah okay, I get it now, thanks for clarifying!

**Review by maxdiebold-erg — APPROVED** [review]

File: src/components/HeaderInfo/HeaderInfo.js [hunk 2]
```diff
@@ -215,6 +215,10 @@ export const HeaderInfo = ({
   const [selectedReportingPeriods, setSelectedReportingPeriods] = useState(
     currentTab?.reportingPeriods ?? []
   );
+  /* defaultReportingPeriodChanged is a flage; user selecte a reporing date or not;
+    it's changed when user manually change location or viewTemplate or when import data
+  */
```
Comment (maxdiebold-erg) [inline src/components/HeaderInfo/HeaderInfo.js]: Some of the spelling is off here:
```suggestion
  /* defaultReportingPeriodChanged is a flag for whether a user has selected a reporing date or not;
    it's changed when user manually changes location or viewTemplate or imports data
  */
```

File: src/components/HeaderInfo/HeaderInfo.js [hunk 3]
```diff
@@ -883,13 +887,19 @@ export const HeaderInfo = ({
...
         // getEmissionsViewDropdownData w/ new reporting periods state
         const { year, quarter } = payload;
-        const importedReportingPeriod = `${year} Q${quarter}`;
-        // Select only the reporting period that was uploaded
+        let importedReportingPeriod = [`${year} Q${quarter}`];
+        if (defaultReportingPeriodChanged) {
+          importedReportingPeriod = [...new Set(selectedReportingPeriods.concat([`${year} Q${quarter}`]))];
+        }
+
+        // Select the reporting period that user was selected
```
Comment (maxdiebold-erg) [inline src/components/HeaderInfo/HeaderInfo.js]:
```suggestion
        // Select the reporting period that user has selected
```

File: src/components/HeaderInfo/HeaderInfo.js [hunk 4]
```diff
@@ -924,14 +934,19 @@ export const HeaderInfo = ({
...
     // set relevant reporting periods state to rerender which will call
     // getEmissionsViewDropdownData w/ new reporting periods state
-    const importedReportingPeriod = `${historicYear} Q${historicQuarter}`;
-    // Select only the reporting period that was uploaded
+    let importedReportingPeriod = [`${historicYear} Q${historicQuarter}`];
+    if (defaultReportingPeriodChanged) {
+      importedReportingPeriod = [...new Set(selectedReportingPeriods.concat([`${historicYear} Q${historicQuarter}`]))];
+    }
+
+    // Select the reporting period that user was selected
```
Comment (maxdiebold-erg) [inline src/components/HeaderInfo/HeaderInfo.js]:
```suggestion
    // Select the reporting period that user has selected
```

**Review by maxdiebold-erg — COMMENTED** [review]
I left a few suggestions fixing some comment spelling errors. This certainly isn't crucial, though, so I'll leave it up to you if you want to update them.

**Review by maxdiebold-erg — DISMISSED** [review]

**Review by maxdiebold-erg — APPROVED** [review]
Looks good! Thanks for making those changes.
