### PR TITLE
fix/6622-Create-List-of-Submissions-Report

### LINKED ISSUE #6622: Complete List of Submissions Report (CAT)
(continuation of #4675 )

### PR DESCRIPTION
**Pull request by Jhernandez29**
Ticket number:
https://github.com/US-EPA-CAMD/easey-ui/issues/6622
Changes:
Created new AdminSubmissionReport folder and added three new files. AdminSubmissionReport.js parent component, filterFormAdminSubmissionReport.js contains form child component for user inputs, and SubmissionReportData.js contains table with data and excel export button.

### CODE REVIEW

**Review by yonatan-dp — DISMISSED** [review]

File: src/components/AdminSubmissionReport/SubmissionReportData.js [hunk 1]
```diff
@@ -0,0 +1,248 @@
...
+      facilityName: "Facility Name",
+      state: "State",
+      locations: "MP Location ",
+      reportingPeriodAbbreviation: "Reporting Period",
+      reportingFrequencyCode: "Reporting Frequency",
+      submissionTypeCode: "Submission Type",
+      submissionId: "Submission ID",
+      submissionDateTime:"Submission Date/Time",
+      severityLevel: "Severity Level",
+      mostRecet: "Most Recent",
```
Comment (yonatan-dp) [inline src/components/AdminSubmissionReport/SubmissionReportData.js]: Typo?  mostRecent?

**Review by yonatan-dp — CHANGES_REQUESTED** [review]

File: src/components/AdminSubmissionReport/SubmissionReportData.js (hunk 1 above)
Comment (Jhernandez29) [reply src/components/AdminSubmissionReport/SubmissionReportData.js]: Corrected in commit https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1553/commits/78669070221f0fec7cee3020294139b3913c8ae5

**Review by yonatan-dp — APPROVED** [review]
