### PR TITLE
fix:componentId and moniteringSystemId read only for submited QA

### LINKED ISSUE #6060: Make component and system ID fields read-only for submitted QA tests
In the workspace, users are able to change component and system IDs for already submitted QA tests.

These fields should be read-only for already submitted tests. The current practice is to first delete these tests if they were submitted with incorrect component/system IDs. This ensures related supplemental data is also deleted and invalid evaluation results are not received.

### PR DESCRIPTION
**Pull request by ergjustin**
## Ticket
[Make component and system ID fields read-only for submitted QA tests](https://github.com/US-EPA-CAMD/easey-ui/issues/6060)

## Changes
`componentId` and `monitoringSystemId` read only for submited QA test data

### CODE REVIEW

File: src/components/ModalDetails/ModalDetails.js [hunk 1]
```diff
@@ -29,6 +29,7 @@ const ModalDetails = ({
   setMainDropdownChange,
   mainDropdownChange,
   setDisableExitBtnStatus,
+  disableColoums
```
Comment (djw4erg) [inline src/components/ModalDetails/ModalDetails.js]: Although it does not negatively affect the change, "Coloums" in the field name should be "Columns" and I would argue for naming it "disabledColumns".  Minimally, correct the spelling.

**Review by djw4erg — CHANGES_REQUESTED** [review]

**Review by djw4erg — APPROVED** [review]
