### PR TITLE
MATS DATA Preview Button not working

### LINKED ISSUE #7074: MATS DATA Preview Button not working
In Dev the User can't preview XML files. While performing regression testing, this issue was discovered.
The XML shows a blank page. 

Image

Developer notes:
When new tab is open no rendering happens. 
Behavior is different on different browsers. 

Best way to fix this issue is to preview the XML content, show it as plain text. This works in all browsers.

### PR DESCRIPTION
**Pull request by Jhernandez29**
ticket:
https://github.com/US-EPA-CAMD/easey-ui/issues/7074

changes:
show XML as type plain text. This works in all browsers.

### CODE REVIEW

File: src/utils/functions.js [hunk 1]
```diff
@@ -578,5 +578,10 @@ export const canSubmitMats = (user, selectedConfig, checkedOutConfigs) => {
     ?.find((facility) => facility.facId === selectedFacilityId)
     ?.permissions.includes("DSQA");
 
+    console.log( user.facilities)
+    console.log(isCheckedOutByUser)
+        console.log(hasRequiredRole)
+    console.log(hasRequiredFacilityPermission)
+
```
Comment (ergjustin) [inline src/utils/functions.js]: Please remove logs

**Review by ergjustin — CHANGES_REQUESTED** [review]

**Review by ergjustin — APPROVED** [review]
