### PR TITLE
Fix/#6523 emission api json hijacking endpoints

### LINKED ISSUE #6523: JSON Hijacking Vulnerable Endpoints - emissions-api
# JSON Hijacking Vulnerability Analysis & Solution

## Overview
JSON hijacking vulnerability has been identified in several endpoints that return arrays directly via GET requests in the easey-emissions-api. This document outlines the vulnerable endpoints and provides a solution to mitigate this security risk.

**Note**:  Please see #6518 for corresponding changes to performance test scripts.

---

## Vulnerable Endpoints 

**Note**:  `The following list of endpoints is not a comprehensive list of all the endpoints that need updating.  For the entire backend API application, do an exhaustive search for all endpoints in the API that returns arrays and make the necessary changes.  As described below, make sure all clients (such as ecmps-ui, campd-ui, and other backend-apis) are also updated to properly handle the new response format`

### 1. Apportioned Emissions Related
```
- api.epa.gov/easey/staging/emissions-mgmt/attributes/applicable
```

### 2. Emissions Related
```
- api.epa.gov/easey/staging/emissions-mgmt/emissions
```

### 3. Ozone Emissions Related
```
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/ozone
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/ozone/by-facility
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/ozone/by-state
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/ozone/nationally
```

### 4. Daily Emissions Related
```
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/daily
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/daily/by-facility
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/daily/by-state
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/daily/nationally
```

### 5. Annual Emissions Related
```
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/annual
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/annual/by-facility
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/annual/by-state
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/annual/nationally
```

### 6. Quarterly Emissions Related
```
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/quarterly
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/quarterly/by-facility
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/quarterly/by-state
- api.epa.gov/easey/staging/emissions-mgmt/emissions/apportioned/quarterly/nationally
```

---

### 1. Use Response Interface

Create a new file `src/interfaces/array-response.interface.ts`:
**Or better, create this interface in easey-common for sharing** 

```typescript
export interface ArrayResponse<T> {
  data: T[];
}
```

---

### 2. Example usage 

Here's how to modify the `ApportionedEmissionsController` to wrap the array response:

```typescript
@Get('/attributes/applicable')
@ApiOkResponse({
  description: 'Retrieves Applicable Emissions Attributes',
  type: ArrayResponse<ApplicableApportionedEmissionsAttributesDTO>
})
@BadRequestResponse()
@NotFoundResponse()
@ApiQuery({
  style: 'pipeDelimited',
  name: 'year',
  required: true,
  explode: false,
})
async getApplicableApportionedEmissionsAttributes(
  @Query()
  applicableApportionedEmissionsAttributesParamsDTO: ApplicableApportionedEmissionsAttributesParamsDTO,
): Promise<ArrayResponse<ApplicableApportionedEmissionsAttributesDTO>> {
  const attributes = await this.service.getApplicableApportionedEmissionsAttributes(
    applicableApportionedEmissionsAttributesParamsDTO,
  );
  return {
    data: attributes
  };
}
```

And for the `EmissionsController`:

```typescript
@Get()
@ApiOkResponse({
  description: 'Retrieves emissions review and submit records',
  type: ArrayResponse<EmissionsReviewSubmitDTO>
})
@ApiQuery({
  style: 'pipeDelimited',
  name: 'orisCodes',
  required: true,
  explode: false,
})
@ApiQuery({
  style: 'pipeDelimited',
  name: 'monPlanIds',
  required: false,
  explode: false,
})
@ApiQuery({
  style: 'pipeDelimited',
  name: 'quarters',
  required: true,
  explode: false,
})
async getEmissions(
  @Query() dto: ReviewAndSubmitMultipleParamsDTO,
): Promise<ArrayResponse<EmissionsReviewSubmitDTO>> {
  const emissions = await this.submissionService.getEmissionsRecords(
    dto.orisCodes,
    dto.monPlanIds,
    dto.quarters,
    false,
  );
  return {
    data: emissions
  };
}
```

**Note**: Make sure swagger documentation is updated along with code changes. 

---

## Frontend Changes Required

Since the backend is now returning an array wrapped in an object, the frontend or any consumer of these API endpoints needs to be updated to handle this new response type. Assuming the frontend is using a common response handler, it should be updated as follows:

#### Before
```javascript
return axios.get(url).then(handleResponse).catch(handleError);

export async function handleResponse(response) {
  if (response.status === 200 || response.status === 201) {
    return response.data;  // response.data was an array
  } else {
    throw new Error("failed");
  }
}
```

#### After
```javascript
return axios.get(url).then(handleResponse).catch(handleError);

export async function handleResponse(response) {
  if (response.status === 200 || response.status === 201) {
    // Check if response is a wrapped array
    if (response.data && Array.isArray(response.data.data)) {
      return response.data.data;  // unwrap array from response object
    }
    // Return original response data for non-array responses
    return response.data;
  } else {
    throw new Error("failed");
  }
}
```

## Testing

Update existing tests to expect the new response structure. For example:

```typescript
it('should return a wrapped array response', async () => {
  const expectedResult = {
    data: [] as EmissionsReviewSubmitDTO[]
  };
  
  jest.spyOn(submissionService, 'getEmissionsRecords')
    .mockResolvedValue(expectedResult.data);
    
  expect(await controller.getEmissions(mockReviewAndSubmitMultipleParamsDTO))
    .toEqual(expectedResult);
});
```

**Note**: The above code is provided as sample and has not been tested. Please adjust as needed and test thoroughly.

### PR DESCRIPTION
**Pull request by Jhernandez29**
Ticket
https://github.com/US-EPA-CAMD/easey-ui/issues/6523

changes 
Updated ExportTab and function.js the useEffect when calling getEmissionReviewSubmit.

### CODE REVIEW

File: src/components/EvaluateAndSubmit/EvaluateAndSubmit.js [hunk 1]
```diff
@@ -591,13 +591,38 @@ export const EvaluateAndSubmit = ({
...
+      }
+    else {
+        if (resp.request.responseURL.includes('emissions-mgmt/emissions')) {
+         data = resp.data.items
+        }
+        else 
+        {
+          data = resp.data
+        }
+      }
```
Comment (yonatan-dp) [inline src/components/EvaluateAndSubmit/EvaluateAndSubmit.js]: Just a thought.  Would it be simpler and more generic to check for the existence of 'items' and then, if not, fall back on '.data'?  We should avoid if checks, especially based on the URL. Something like this?

`const data = resp.data?.items ?? resp.data;`

Make sure to test that it handles all cases ...

File: src/components/export/ExportTab/ExportTab.js [hunk 2]
```diff
@@ -142,7 +142,13 @@ export const ExportTab = ({
       {
         if(workspace)
         {
-         return resp.data
+            if (resp.request.responseURL.includes('emissions-mgmt/workspace/emissions')) {
+              return resp.data.items
+           }
+            else 
+           {
+               return resp.data
```
Comment (yonatan-dp) [inline src/components/export/ExportTab/ExportTab.js]: See comment above.  It may be more generic to handle all cases without depending on the URL 

  return resp.data?.items ?? resp.data;

File: src/utils/functions.js [hunk 3]
```diff
@@ -277,10 +277,19 @@ export const getEvalStatus = async (paramsArray) => {
...
+        if (!response?.data?.items.length) return;
+        if (identifier) return items[0].evalStatusCode;
+        return response.data.items[0]?.evalStatusCode;
+      }
+      else 
+      {
+        const items = response?.data.filter((el) => el[identifier] === id);
+        if (!response?.data?.length) return;
+        if (identifier) return items[0].evalStatusCode;
+        return response.data[0]?.evalStatusCode;
```
Comment (yonatan-dp) [inline src/utils/functions.js]: See comment above ...

**Review by yonatan-dp — CHANGES_REQUESTED** [review]
Please see comments...

**Review by yonatan-dp — APPROVED** [review]

**Review by yonatan-dp — CHANGES_REQUESTED** [review]
Checks have failed.

**Review by yonatan-dp — DISMISSED** [review]

**Review by yonatan-dp — APPROVED** [review]
