### PR TITLE
Fix/#6449 loading spinner message

### LINKED ISSUE #6449: Bug: Loading spinner missing in lower grid of Emissions screen
There used to also be a loading spinner in the lower grid of the Emissions screen while data was still loading for a view.   As of now, the following is displayed to a user while the data is loading. 

Image

When user clicks the filter, "loading data" should appear until the data is ready to display.

### PR DESCRIPTION
**Pull request by Jhernandez29**
ticket
https://github.com/US-EPA-CAMD/easey-ui/issues/6449#issuecomment-2656905205

changes 
Updated message when no data is present. Instead of adding no data record and rendering another message after 1 second. The message is static.

### CODE REVIEW

File: src/components/EmissionsViewTable/EmissionsViewTable.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ export const EmissionsViewTable = ({ monitorPlanId, filterApply, setFilterApply
         else
         {
             setViewData(reduxCurrentTab?.viewData || []);
-            setMessage('Select a Reporting Period, Location, and Template and Apply Filter to view the data');
+            setMessage('Select a Reporting Period, Location, and Template, then click the Apply Filter button to view the data.');
```
Comment (maxdiebold-erg) [inline src/components/EmissionsViewTable/EmissionsViewTable.js:41]: For consistency, I'd say either add the trailing period everywhere or leave it off. The initial message does **not** have a trailing period.

File: src/components/EmissionsViewTable/EmissionsViewTable.js [hunk 2]
```diff
@@ -47,10 +47,9 @@ export const EmissionsViewTable = ({ monitorPlanId, filterApply, setFilterApply
         {
             if ( viewData?.length === 0) {
                 const timeOutApply = setTimeout(() => {
-                    setMessage('Select a Reporting Period, Location, and Template and Apply Filter to view the data');
                     setPendingMessage(false)
                 }, 1000);
-                setMessage('There are no records to display');
+                setMessage('There are no records to display.\nSelect another Reporting Period, Location, and Template, then click the Apply Filter button to view the data.');
```
Comment (maxdiebold-erg) [inline src/components/EmissionsViewTable/EmissionsViewTable.js]: You could just set the HTML here and avoid the changes below:
```suggestion
        setMessage(
          <div>
            <p>There are no records to display</p>
            <p>
              Select another Reporting Period, Location, and Template, then
              click the Apply Filter button to view the data
            </p>
          </div>
        );
```
This also avoids the extra empty `div` that is being added in the `customNoDataMessage`.

**Review by maxdiebold-erg — DISMISSED** [review]
Looks good, thanks for updating that text!

I left a couple suggestions, but they're nitpicks so I'll leave the call up to you.

**Review by maxdiebold-erg — APPROVED** [review]
