### PR TITLE
fix:optimize table data rendering and checkedOutBy updates

### LINKED ISSUE #6936: Evaluate and Submit page "Checked Out" column
A beta tester noticed that the "checked out" column on the evaluate and submit page is not populated when a configuration is actually checked out.

Image

Image

### PR DESCRIPTION
**Pull request by ergjustin**
## Ticket
[Evaluate and Submit page "Checked Out" column](https://github.com/US-EPA-CAMD/easey-ui/issues/6936)

## Change 
Optimize table data rendering and checkedOutBy updates

### CODE REVIEW

File: src/components/EvaluateAndSubmit/EvaluateAndSubmit.js [hunk 1]
```diff
@@ -168,10 +158,46 @@ export const EvaluateAndSubmit = ({
...
+
+    if (hasChanges) {
+      list.ref.current = updatedData;
+    }
+  }
+
+  if (hasChanges) {
+    forceReloadTables();
+  }
+}, [checkedOutLocations, dataList]);
```
Comment (Jhernandez29) [inline src/components/EvaluateAndSubmit/EvaluateAndSubmit.js:208]: The code works great but there is an issue when the user clicks on the "Apply Filter" bottom. The data doesn't include the checkout By because the use Effect is not trigger again. 

Would be best to add this 
``` 
const checkOutBy = () => {
if (!checkedOutLocations || checkedOutLocations.length === 0) return;

  const mapping = new Map();
  for (const obj of checkedOutLocations) {
    mapping.set(obj.monPlanId, obj.checkedOutBy);
  }

  let hasChanges = false;
  
  for (const list of dataList) {
    const updatedData = list.ref.current.map(curr => {
      const newCheckedOutBy = mapping.has(curr.monPlanId) 
        ? mapping.get(curr.monPlanId) 
        : "";
      
      // Only create new object if value actually changed
      if (curr.checkedOutBy !== newCheckedOutBy) {
        hasChanges = true;
        return {
          ...curr,
          checkedOutBy: newCheckedOutBy
        };
      }
      return curr;
    });

    if (hasChanges) {
      list.ref.current = updatedData;
    }
  }

  if (hasChanges) {
    forceReloadTables();
  }
  }

 useEffect(() => {
  checkOutBy()
}, [checkedOutLocations, dataList]);```

**Review by Jhernandez29 — CHANGES_REQUESTED** [review]
On applyFilter function add the new checkOutBy() function. This will trigger the update of the table with the checkoutby right value.  
``` 
 const applyFilter = async (orisCodes, monPlanIds, submissionPeriods) => {
    storedFilters.current = {
      orisCodes: orisCodes,
      monPlanIds: monPlanIds,
      submissionPeriods: submissionPeriods,
    };
    // Reset all of the tables to a refreshing state
    for (const value of dataList) {
      //Iterate here to show the client tables are loading
      const { progressPending } = value;
      progressPending.current = true;
    }
    forceReloadTables();
    // We have to load monitor plans first to get all of the active locations
    const [{ data: { items: officialMonitorPlans } }, { data: { items: workspaceMonitorPlans } }] =
      await Promise.all([
        dataList[0].call(orisCodes, monPlanIds, DatabaseContext.OFFICIAL),
        dataList[0].call(orisCodes, monPlanIds, DatabaseContext.WORKSPACE),
      ]);
    // Filter to plans that are `active` in the workspace or that are `active` in official but `inactive` in the workspace (becoming inactive).
    const monitorPlans = workspaceMonitorPlans.filter((mp) => {
      return (
        mp.active ||
        officialMonitorPlans.some(
          (omp) => omp.monPlanId === mp.monPlanId && omp.active
        )
      );
    });
    const activePlanIdSet = new Set(monitorPlans.map((mp) => mp.id));
    // Call submissionQueueOrder
    let submissionQueueOrderData;
    if (componentType === "Submission") {
      const submissionQueueOrder = await getSubmissionQueueOrder(orisCodes);
      submissionQueueOrderData = submissionQueueOrder && submissionQueueOrder.data && submissionQueueOrder.data.items;
      // submissionQueueOrderData && submissionQueueOrderData.length && 
      setDescription(monitorPlans, submissionQueueOrderData, 'MP');
    }
    formatDataRows(dataList[0].ref, monitorPlans, "MP");
    dataList[0].progressPending.current = false;
    forceReloadTables();
    const promises = [];
    for (let i = 1; i < dataList.length; i++) {
      //Iterate over other non monitor plan sets of data
      promises.push(retrieveAndFormatData(i, activePlanIdSet, submissionQueueOrderData));
    }
    await Promise.all(promises);
    checkOutBy()

  };`

**Review by Jhernandez29 — CHANGES_REQUESTED** [review]
@ergjustin  Looks like the latest run failed in SonarCloud with 4 issues detected https://sonarcloud.io/project/issues?id=US-EPA-CAMD_easey-ecmps-ui&pullRequest=1774&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true

**Review by Jhernandez29 — APPROVED** [review]
Looks good
