### PR TITLE
Fix/#6449 emission loading spinner missing

### LINKED ISSUE #6449: Bug: Loading spinner missing in lower grid of Emissions screen
There used to also be a loading spinner in the lower grid of the Emissions screen while data was still loading for a view.   As of now, the following is displayed to a user while the data is loading. 

Image

When user clicks the filter, "loading data" should appear until the data is ready to display.

### PR DESCRIPTION
**Pull request by Jhernandez29**
Ticket
https://github.com/US-EPA-CAMD/easey-ui/issues/6449

Changes
Updated EmissionsViewTable with useEffect to update the spinner when the data is loading. Added a second useEffect to update the message to display if there is no data and when the user needs to click the apply filter.

### CODE REVIEW

File: src/components/EmissionsTabRender/EmissionsTabRender.js [hunk 1]
```diff
@@ -33,10 +33,15 @@ export const EmissionsTabRender = ({
...
 
   const [viewTemplateSelect, setViewTemplateSelect] = useState(null);
+  const [filterApply, setFilterApply] = useState(false);
 
   // Determines if a user has just navigated to the page without applying any filters yet
   const isInitialLoadOfPage = currentTab?.isViewDataLoaded === undefined;
 
+  const memoizedSetFilterApply = useCallback((value) => {
+    setFilterApply(value);
+  }, [setFilterApply]);
```
Comment (maxdiebold-erg) [inline src/components/EmissionsTabRender/EmissionsTabRender.js]: There is no need to memoize state setters, they are stable across renders.
```suggestion
```

**Review by maxdiebold-erg — DISMISSED** [review]
Works well!

I left one suggestion below: memoizing the `setFilterApply` call shouldn't be necessary, React guarantees that `setState` calls are stable across renders (but it isn't hurting anything).

File: src/components/EmissionsTabRender/EmissionsTabRender.js (hunk 1 above)
Comment (Jhernandez29) [reply src/components/EmissionsTabRender/EmissionsTabRender.js]: Removed memoize state setter

**Review by maxdiebold-erg — APPROVED** [review]
Thanks for making that change!
