### PR TITLE
 Fix token refresh race condition causing authentication errors

### LINKED ISSUE #7018: Errors on Dev
On Dev: yesterday and today I keep on getting these errors (alternating back and forth) while actively working with ECMPS. I am then forced to logout and log back in before I can do anything else.

Image
Image

### PR DESCRIPTION
**Pull request by yonatan-dp**
Implemented atomic lock mechanism in refreshToken() to ensure only one request claims the refresh lock, and fixed catch block to return current token from localStorage instead of undefined. Undefined prevented self-healing on transient failures.

### CODE REVIEW

File: src/utils/api/easeyAuthApi.js [hunk 1]
```diff
@@ -181,8 +181,8 @@ export const refreshToken = async () => {
       await new Promise((resolve) => setTimeout(resolve, 100));
       waitDuration += 100;
     }
```
Comment (maxdiebold-erg) [inline src/utils/api/easeyAuthApi.js]: I think this block is now redundant. If the current token is expired, the block below will wait for an ongoing call, but if not it will just use the existing token.

**Review by maxdiebold-erg — COMMENTED** [review]
The changes look good! One question below about how they interact with pre-existing code.

File: src/utils/api/easeyAuthApi.js (hunk 1 above)
Comment (yonatan-dp) [reply src/utils/api/easeyAuthApi.js]: That is correct!  I have removed that block.

**Review by maxdiebold-erg — APPROVED** [review]
